### ISSUE TITLE
Allow additional data to be stored per melody script run

### ISSUE THREAD

**Issue by staabm** [sensiolabs/melody#39]
I would like to store some temporary files which are required run melody-scripts from within another app (php-console).

If I could add somehow files to the melody's working-dir those were automatically cleaned up by the melody garbage collector, which would be highly usefull in my case. otherwise i need to create another garbage collector for my "own" temp files.

Would you consider this something in scope of melody?

**Comment by jeremy-derusse** [comment]
I'm not sure to understand your need...
If you want to store temporary file (automaticly deleted by the garbage collector of melody), just put it in the working directory (you can retrieve it name with $argv[0])

**Comment by staabm** [comment]
I need a way to retrieve the path to the working directory (since I am not using the CLI tools of melody but the API)

**Comment by lyrixx** [comment]
@staabm You have already everything you need in the current API, [see this file](https://github.com/sensiolabs/melody/blob/2a57fa4dd18f404b061f9a75d25f65bbdb86d8e2/src/SensioLabs/Melody/Melody.php#L54)

**Comment by staabm** [comment]
@lyrixx right, but I cannot access the wdFactory from my code.

**Comment by lyrixx** [comment]
What do you propose ?

because the wdFactory is easy to instanciate, see [this](https://github.com/sensiolabs/melody/blob/e5bb1a4e0d3c6a0240ec47f21f04fd42d27cdfa0/src/SensioLabs/Melody/Melody.php#L33-L41)

**Comment by staabm** [comment]
If I would know/could access the `storagePath` which is required to instantiate the `wdFactory`, everything would be fine IMO.

wdyt about just adding a getter for the `storagePath`?

**Comment by staabm** [comment]
scratch that. I think I need a getter to the `WorkingDirectory`itself, so e.g.

```
// could also be protected
public function getWorkingDirectory() {
  return $this->wdFactory->getWorkingDirectory();
}

**Comment by lyrixx** [comment]
`getWorkingDirectory` is fine for me, could you open a PR?

**Comment by staabm** [comment]
Just found a easy way to cleanup my stuff myself.
