### ISSUE TITLE
Run 2 differents scripts with same packages concurrently

### ISSUE THREAD

**Issue by jderusse** [sensiolabs/melody#48]

**Comment by staabm** [comment]
triggered by https://github.com/sensiolabs/melody/pull/42#issuecomment-68710712

**Comment by lyrixx** [comment]
@jeremy-derusse For me it's a `won't fix`. Except if someone come with a valid use case and a simple implementation.

**Comment by jeremy-derusse** [comment]
Just to keep a log/trace of the feature.

**Comment by lyrixx** [comment]
Won't fix.
