### ISSUE TITLE
Authenticate melody to github to skip rate limit

### ISSUE THREAD

**Issue by jderusse** [sensiolabs/melody#51]
When downloading a gist, we may have a failure
```
[InvalidArgumentException]                                                                                                                                                                                  
  There is an issue with your gist URL: API rate limit exceeded for W.X.Y.Z. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)  
```

We could take the composer's one `~/.composer/auth.json` or asking the user to create ours `auth.json`.

**Comment by lyrixx** [comment]
:+1: for the feature

**Comment by staabm** [comment]
:+1:

**Comment by lyrixx** [comment]
Does someone want to take care of this one?

**Comment by lyrixx** [comment]
Well, This issue is not relevant anymore
https://github.com/composer/composer/issues/4884#issuecomment-195229989
\o/

**Comment by xabbuh** [comment]
@lyrixx I am not sure that they really dropped all rate limits. From the statement you linked to I'd assume that they did so for some endpoints only.

**Comment by lyrixx** [comment]
Hmm; you may be right. Any way, we could let this issue closed. And we will re-open it if needed.
