### ISSUE TITLE
Wrong exit code

### ISSUE THREAD

**Issue by jeremy-derusse** [sensiolabs/melody#52]
Melody exit with code 0 even if the script exit with a failure.
We should exit the melody's process with the same code than the runned script.

**Comment by lyrixx** [comment]
Are you sure? I mean, melody ran successfully, even if the script did not.

**Comment by staabm** [comment]
agree with @jeremy-derusse. I cannot think of a use case one would be interessted if melody runs but the code did not. the tools runs melody scripts and the result for the tool depends on the result of the script IMO

**Comment by jeremy-derusse** [comment]
as `ssh your_server.com a_bad_command` returns a failure code even if the `ssh` process ran successfulty, I thinks melody should forward the error code.

The main reason, is to show to the user (when his prompt is well configured or when he use a CI) that something wrong appends

**Comment by lyrixx** [comment]
ok, no poblem ; It was just a question. So :+1: for me ;)
