### ISSUE TITLE
Sample of use case

### ISSUE THREAD

**Issue by lyrixx** [sensiolabs/melody#56]
@jeremy-derusse and I have created few useful gist (private and / or public use).

I think it could be useful to have a place in the documentation to "link" theses gist.

What do you think?

**Comment by jeremy-derusse** [comment]
:+1: Great idea

**Comment by lyrixx** [comment]
Does someone want to take care of this one?

**Comment by ostrolucky** [comment]
We can start by posting these links here

**Comment by jderusse** [comment]
# Run SSH client.
https://gist.github.com/jderusse/33aa11268318c4825807
```
melody run 33aa11268318c4825807 run@myserver
```

# Extension using by an app
https://gist.github.com/jderusse/32a9d0b105e359f322af

Similar to https://github.com/maglnet/ComposerRequireChecker
Don't work anymore
```
melody run 32a9d0b105e359f322af
```

# symfony security checker
https://gist.github.com/jderusse/7c86752c7c38eff8db65
```
melody run 7c86752c7c38eff8db65 security:check
```

# use interractive console
https://gist.github.com/jderusse/ed84850c2c594fdc682c

don't work anymore (have to deal with deprecation)
