### ISSUE TITLE
Define repositories section to allow private packages

### ISSUE THREAD

**Issue by danielcosta** [sensiolabs/melody#60]
We should be able to define repositories for private repositories like we do on current composer.json definition schema: https://getcomposer.org/doc/04-schema.md#repositories

Maybe something like this or any variation that apply:

```
<?php
<<<CONFIG
repositories:
    - "private-vendor/private-repo"
        - "type": "vcs"
        - "url": "git@bitbucket.org:private-vendor/private-repo.git"
packages:
    - "private-vendor/private-repo: ~1.0"
CONFIG;
```

**Comment by lyrixx** [comment]
Good idea. Can you provide a PR for this ?

**Comment by aaa2000** [comment]
There are already a PR for this ? https://github.com/sensiolabs/melody/pull/38

**Comment by danielcosta** [comment]
@aaa2000 #38 was exactly what I proposed.
This issue can be closed.
