### ISSUE TITLE
Cannot get command line option -h

### ISSUE THREAD

**Issue by wenbinye** [sensiolabs/melody#71]
I wrote this simple php script :
```php
<?php
<<<CONFIG
packages:
    - "symfony/finder: ~2.5"
CONFIG;

$options = getopt('h');
var_export($options);
```

run with `php test.php -h` can output option h:
```
$ php test.php -h 
array(
  'h' => false
)
```

Expect  `melody run test.php -- -h` same output, which is not. It output `melody run` help.

**Comment by lyrixx** [comment]
Thanks for your feedback. I confirm the issue. It's look like it's a bug in the Symfony/Console Component. I have not time right now to debug this one. Could someone take a look at it?

**Comment by aaa2000** [comment]
Same issue for arguments

```
melody run -vvv test.php -- -V
melody run -vvv test.php -- --version
```

But this commit https://github.com/symfony/console/commit/41d8646d0432f62bca57d6d5bd9feb6dd4b5efe1 should resolve the bug

**Comment by lyrixx** [comment]
Nice catch. But it's weird because the commit is one year old, so we should get it already. Could you try to update deps and try again ?

**Comment by aaa2000** [comment]
The commit is only on master, v3.0.1, v3.0.0, v3.0.0-BETA1 because it introduces BC Breaks https://github.com/symfony/console/commit/56cd0ec9b4a7f08a7fd66b57e8f938b1e488d301

Using symfony/console:~3.0, fix the bug
```
composer require symfony/console:~3.0
```
