### ISSUE TITLE
tag a release

### ISSUE THREAD

**Issue by staabm** [sensiolabs/melody#74]
would be great if you could tag a release.

atm my tooling based on melody is really unstable because of some BC changes happing from time to time :-/

**Comment by lyrixx** [comment]
Hello.

That's why I don't want to tag melody, In order to be able to break the BC.
**But** The BC has [not been broke](https://github.com/sensiolabs/melody/commits/master) for a while
So I think we can tag the 1.0.0. It will happen soon ;)

**Comment by staabm** [comment]
just FYI, I referred to the BC break with in the `run` method.
https://github.com/sensiolabs/melody/commit/8744cc6a08b32842331249d67c30a139bcb6d295#diff-cc73de8c4f68f7e29af0a9633f06af73R50

**Comment by lyrixx** [comment]
I want to "fix" #76 before a new tagging a release.

**Comment by staabm** [comment]
here we go https://github.com/sensiolabs/melody/pull/81

**Comment by Nek-** [comment]
Tag is a requirement for `brew` formula. https://github.com/Homebrew/brew/blob/master/docs/Formula-Cookbook.md#basic-instructions

**Comment by ostrolucky** [comment]
You don't need to tag 1.0. Just tag 0.1 which allows you to break BC in 0.2

**Comment by Nek-** [comment]
Except current build of melody specify v1.0.0.

**Comment by fabpot** [comment]
I'm going to archive this project now to make it clear that the project is not maintained anymore. Anyone can fork it.
