### ISSUE TITLE
support composer like notations

### ISSUE THREAD

**Issue by staabm** [sensiolabs/melody#76]
atm one needs to write

```
<<<CONFIG
packages:
    - "codeguy/arachnid: 1.*"
CONFIG;
```

for melody to get it working.

More composer like would be something like 

```
<<<CONFIG
packages:
    - "codeguy/arachnid": "1.*"
CONFIG;
```

as this is 1:1 the notation composer uses on CLI. this might semantically not be the JSON one would expect, but syntax wise it would be great, as you can pickup the lines from the composer.json

related to https://github.com/sensiolabs/melody/pull/75

**Comment by staabm** [comment]
atm you get an error like `The package at key "0" should be a string.`

**Comment by lyrixx** [comment]
I don't remember why I did not do that in the first place. I guess there are some culprit somewhere.

But if you want to try and submit a working PR, I'll be glad to merge it.

**Comment by jderusse** [comment]
or 
```
packages:
    codeguy/arachnid: 1.*
```

**Comment by staabm** [comment]
@jderusse I wozld be ok to also support the format you suggest, but I feel the initially format is more important because its 1:1 what people write in composer.json in most cases

**Comment by fabpot** [comment]
I'm going to archive this project now to make it clear that the project is not maintained anymore. Anyone can fork it.
