### ISSUE TITLE
Support declare(strict_types=1)

### ISSUE THREAD

**Issue by pimolo** [sensiolabs/melody#91]
When I start a file with:
```php
<?php

declare(strict_types=1);

<<<CONFIG
packages:
    - .....
CONFIG;
```

Then I get the following error in console (after `melody run`)
```sh
In ResourceParser.php line 23:

  Impossible to parse the content of the document.

  The php script should look like:

  <?php
  <<<CONFIG
  packages:
      - "symfony/finder: ~2.5"
  CONFIG;

  $finder = Symfony\Component\Finder\Finder::create();
run [--no-cache] [--prefer-source] [-t|--trust] [--] <script> [<arguments>]...
```

https://gist.github.com/pimolo/d06bb4d2e803369a66758095c007f2d1 can be used in order to reproduce.

**Comment by jderusse** [comment]
Melody's parse does not allow extra string before the `<<<CONFIG` header (see https://github.com/sensiolabs/melody/blob/ccf10f654ccfa4c90cbac96320aaff1f927594ce/src/SensioLabs/Melody/Resource/ResourceParser.php#L16)

PR welcome!

**Comment by pimolo** [comment]
@jderusse I'm actually already working on it 😄 🔥

**Comment by fabpot** [comment]
I'm going to archive this project now to make it clear that the project is not maintained anymore. Anyone can fork it.
